### ISSUE TITLE
Confrontation entre le consentement et les attentes

### ISSUE THREAD

**Issue by DavidBruant** [DavidBruant/interactions-humaines-saines-utiles-long-terme#22]
Parfois, A **souffre** que B n'agisse pas d'une certaine manière. A a une [attente](https://github.com/DavidBruant/interactions-humaines-saines-utiles-long-terme/blob/principale/mod%C3%A8le/attentes.md) envers B

B est un individu entier et **souffrirait** de se voir imposer des actions sans son [consentement](https://github.com/DavidBruant/interactions-humaines-saines-utiles-long-terme/blob/principale/consentement.md)

**Comment by scenaristeur** [comment]
Bonjour David, 
Ne penses-tu pas que l'on pourrait appliquer les principes de l'holacratie à une plus large échelle https://fr.m.wikipedia.org/wiki/Holacratie
En gros, Un individu occupe un rôle dans un cercle, lorsqu'il ressent une 'souffrance', il enregistre une 'tension' . Des règles permettent ensuite de régler cette tension au sein du cercle, sinon au niveau du cercle supérieur... Je bosse sur une appli dans le style, si ça t'intéresse . 
David
